### ISSUE TITLE
Getting an error on running travis-ci through docker command http+docker://localunixsocket - is it running?

### ISSUE THREAD

**Issue by tawanorg** [acme101/nextjs-hello-world#2]
```
Building prod
Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
The command "sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml build prod" exited with 1.
Done. Your build exited with 1.
```

Any ideas thanks

**Comment by hoatle** [comment]
hello @timtawan, thank you for your report, let me check on this soon. Btw, I got your email, too.

**Comment by tawanorg** [comment]
@hoatle hey man. thank you soooo much. i am newbie to this area of work. 

Using Next.js + Docker and ideally to deploy to google cloud. Modified your code a bit in .sh and configuration. removed Heroku config, just focusing on Google Cloud kubernetes. Hopefully I could push to live tonight. Thanks mates I'm stay tune for ya. ;)

**Comment by hoatle** [comment]
travis-ci works with my current check. Maybe you should share your project I can look at it.

For GKE deployment, you need to follow this similar config: https://github.com/acme101/dev-setup/blob/master/docs/how-to-deploy-on-gcp.md#auto-deployment-with-ci-system-1

Make sure to encode base64 for the GCP key file.

This is the current travis-ci settings:

![image](https://user-images.githubusercontent.com/83062/28241735-153784a4-69c4-11e7-93f1-939f66745f3a.png)

**Comment by hoatle** [comment]
@timtawan any good news?

**Comment by hoatle** [comment]
I'm seeing the same problem, let me check this again.

**Comment by hoatle** [comment]
@timtawan I see the problem, you forgot to set environment variables of DOCKER_USER and DOCKER_REPO to build up DOCKER_IMAGE_PROD

The error message is so misleading but I finally found the problem now, when you fix it, it should work.

cc @duc4nh

**Comment by hoatle** [comment]
closed as that's was the exact problem (missing DOCKER_USER and DOCKER_REPO env settings on the CI project)
